In [4]:
import numpy as np

In [5]:
print(numpy.__version__)

1.21.5


In [8]:
I = np.identity(4)

In [10]:
Zero_4 = np.zeros([4, 4])

In [12]:
Zero_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.rand(4, 4)

In [18]:
np.asarray([1, 2, 3, 4])

array([1, 2, 3, 4])

In [17]:
np.asarray([1, 2, 3, 4]).reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [19]:
A = np.asarray([1, 2, 3, 4]).reshape(2, 2)

In [22]:
B = np.identity(2)

In [24]:
A, B

(array([[1, 2],
        [3, 4]]),
 array([[1., 0.],
        [0., 1.]]))

In [21]:
A + B

array([[2., 2.],
       [3., 5.]])

In [25]:
np.add(A, B)

array([[2., 2.],
       [3., 5.]])

In [26]:
A - B

array([[0., 2.],
       [3., 3.]])

In [27]:
np.subtract(A, B)

array([[0., 2.],
       [3., 3.]])

In [28]:
A * B

array([[1., 0.],
       [0., 4.]])

In [29]:
np.dot(A, B)

array([[1., 2.],
       [3., 4.]])

In [30]:
A @ B

array([[1., 2.],
       [3., 4.]])

In [31]:
C = np.random.rand(2, 2)

In [33]:
np.dot(A, C)

array([[0.68825333, 1.97343937],
       [1.65443554, 3.97931452]])

In [34]:
A_inv = np.linalg.inv(A)

In [35]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [36]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [37]:
np.dot(A_inv, A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [38]:
A.T

array([[1, 3],
       [2, 4]])